// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPOBalance.Data;

#nullable disable

namespace NPOBalance.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20251221111718_AddInsuranceRateExtendedFields")]
    partial class AddInsuranceRateExtendedFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("NPOBalance.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorporateRegistrationNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FiscalYearEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FiscalYearStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepresentativeName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("NPOBalance.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Dependents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmploymentEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmploymentStartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedTotalSalary")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidentId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartingSalaryStep")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "EmployeeCode")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("NPOBalance.Models.InsuranceRateSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmploymentInsuranceMinBaseAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmploymentInsuranceMinPremium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmploymentInsuranceRateEmployee")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmploymentInsuranceRateEmployer")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HealthInsuranceMinBaseAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HealthInsuranceMinPremium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HealthInsuranceRateEmployee")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HealthInsuranceRateEmployer")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IndustrialAccidentRateEmployer")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongTermCareRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MonthlyIncomeMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MonthlyIncomeMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NationalPensionMinBaseAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NationalPensionMinPremium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NationalPensionRateEmployee")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NationalPensionRateEmployer")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundingDigit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundingRule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("InsuranceRateSettings");
                });

            modelBuilder.Entity("NPOBalance.Models.PayItemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SectionName")
                        .IsUnique();

                    b.ToTable("PayItemSettings");
                });

            modelBuilder.Entity("NPOBalance.Models.PayItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEarning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("PayItemTypes");
                });

            modelBuilder.Entity("NPOBalance.Models.PayrollEntryDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedAnnualSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("FundingSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayItemValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("CompanyId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("PayrollEntryDrafts");
                });

            modelBuilder.Entity("NPOBalance.Models.PayrollHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Year", "Month", "RunNumber")
                        .IsUnique();

                    b.ToTable("PayrollHeaders");
                });

            modelBuilder.Entity("NPOBalance.Models.PayrollLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoCalculated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayrollHeaderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayItemTypeId");

                    b.HasIndex("PayrollHeaderId");

                    b.ToTable("PayrollLines");
                });

            modelBuilder.Entity("NPOBalance.Models.Employee", b =>
                {
                    b.HasOne("NPOBalance.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NPOBalance.Models.InsuranceRateSetting", b =>
                {
                    b.HasOne("NPOBalance.Models.Company", "Company")
                        .WithMany("InsuranceRateSettings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NPOBalance.Models.PayItemType", b =>
                {
                    b.HasOne("NPOBalance.Models.Company", "Company")
                        .WithMany("PayItemTypes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NPOBalance.Models.PayrollEntryDraft", b =>
                {
                    b.HasOne("NPOBalance.Models.Company", "Company")
                        .WithMany("PayrollEntryDrafts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPOBalance.Models.Employee", "Employee")
                        .WithMany("PayrollEntryDrafts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NPOBalance.Models.PayrollHeader", b =>
                {
                    b.HasOne("NPOBalance.Models.Company", "Company")
                        .WithMany("PayrollHeaders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NPOBalance.Models.PayrollLine", b =>
                {
                    b.HasOne("NPOBalance.Models.Employee", "Employee")
                        .WithMany("PayrollLines")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NPOBalance.Models.PayItemType", "PayItemType")
                        .WithMany("PayrollLines")
                        .HasForeignKey("PayItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NPOBalance.Models.PayrollHeader", "PayrollHeader")
                        .WithMany("PayrollLines")
                        .HasForeignKey("PayrollHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayItemType");

                    b.Navigation("PayrollHeader");
                });

            modelBuilder.Entity("NPOBalance.Models.Company", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("InsuranceRateSettings");

                    b.Navigation("PayItemTypes");

                    b.Navigation("PayrollEntryDrafts");

                    b.Navigation("PayrollHeaders");
                });

            modelBuilder.Entity("NPOBalance.Models.Employee", b =>
                {
                    b.Navigation("PayrollEntryDrafts");

                    b.Navigation("PayrollLines");
                });

            modelBuilder.Entity("NPOBalance.Models.PayItemType", b =>
                {
                    b.Navigation("PayrollLines");
                });

            modelBuilder.Entity("NPOBalance.Models.PayrollHeader", b =>
                {
                    b.Navigation("PayrollLines");
                });
#pragma warning restore 612, 618
        }
    }
}
